---
    - name: Instalando Zabbix Agent para Amazon
      yum:
        name: "{{ url_agent_amazonna }}"
        state: present

    - name: Aplicando config do Zabbix
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - Restart Zabbix Agent

    - name: Iniciar Zabbix com sistema
      service:
        name: zabbix-agent
        enabled: yes
